name             'w_varnish'
maintainer       'Joel Handwell'
maintainer_email 'joelhandwell@gmail.com'
license          'apachev2'
description      'Installs/Configures w_varnish'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.17'

depends 'git'
depends 'apt'
depends 'varnish'
depends 'monit'
depends 'firewall'
depends 's3_file'
depends 'hostsfile'
